# Generated by Django 5.0.1 on 2024-01-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_example', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testexample',
            old_name='firstname',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='testexample',
            old_name='lastname',
            new_name='nickname',
        ),
    ]
